version: '3.8'

services:
  backend:
    image: dhruvlotia/backend:latest
    ports:
      - "4999:4999"  
    environment:
      - ./backend:/usr/src/app  
    depends_on:
      - mongo  

  frontend:
    image: dhruvlotia/frontend:latest 
    ports:
      - "3000:3000"  
    volumes:
      - ./frontend:/usr/src/app  

  mongo:
    image: mongo:latest 
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db  

volumes:
  mongo_data: