apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: dhruvlotia/frontend:latest  
          ports:
            - containerPort: 3000  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dhruvlotia/backend:latest  
          ports:
            - containerPort: 4999  
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  
  ports:
    - port: 3000  
      targetPort: 3000 
      nodePort: 30001  
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP 
  ports:
    - port: 4999  
      targetPort: 4999  
  selector:
    app: backend