name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker image
        run: |
          docker build -t dhruvlotia/frontend:latest ./frontend

      - name: Push Frontend Docker image
        run: |
          docker push dhruvlotia/frontend:latest

      - name: Build Backend Docker image
        run: |
          docker build -t dhruvlotia/backend:latest ./backend

      - name: Push Backend Docker image
        run: |
          docker push dhruvlotia/backend:latest